package constants

const (
	FILTER_TYPE_SIMPLE       = "SIMPLE"
	FILTER_TYPE_COLUMN       = "COLUMN"
	FILTER_TYPE_BETWEEN      = "BETWEEN"
	FILTER_TYPE_NOT_BETWEEN  = "NOT_BETWEEN"
	FILTER_TYPE_IN           = "IN"
	FILTER_TYPE_NOT_IN       = "NOT_IN"
	FILTER_TYPE_NULL         = "NULL"
	FILTER_TYPE_NOT_NULL     = "NOT_NULL"
	FILTER_TYPE_DATE         = "DATE"
	FILTER_TYPE_NUMERIC      = "NUMERIC"
	FILTER_TYPE_DATE_BETWEEN = "DATE_BETWEEN"
	FILTER_TYPE_TERM         = "TERM"

	FILTER_CONNECTOR_AND = "AND"
	FILTER_CONNECTOR_OR  = "OR"

	FILTER_OPERATOR_EQUAL       = "="
	FILTER_OPERATOR_NOT_EQUAL   = "<>"
	FILTER_OPERATOR_MAJOR       = ">"
	FILTER_OPERATOR_MAJOR_EQUAL = ">="
	FILTER_OPERATOR_MINOR       = "<"
	FILTER_OPERATOR_MINOR_EQUAL = "<="
	FILTER_OPERATOR_LIKE        = "LIKE"
	FILTER_OPERATOR_ILIKE       = "ILIKE"
)
